/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ConectarDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import view.DetalheMusicCurtida;
import javax.swing.table.DefaultTableModel;

public class MusicasCurtidas extends javax.swing.JFrame {
    
    public void carregarTabelaMusicasCurtidas() {
    DefaultTableModel modelo = (DefaultTableModel) TabelaMusicasCurtidas.getModel();
    modelo.setRowCount(0); // limpa a tabela

    String sql = "SELECT * FROM cd_musicas_curtidas";

    try (Connection conn = ConectarDB.conectar();
         PreparedStatement stmt = conn.prepareStatement(sql);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getString("nome_musica"),
                rs.getString("artista"),
                rs.getString("genero"),
                rs.getString("tempo_total_musica"),
                rs.getString("data_lancamento")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao carregar músicas: " + e.getMessage());
    }
}


    public MusicasCurtidas() {
        initComponents();
        carregarTabelaMusicasCurtidas();

                TabelaMusicasCurtidas.addMouseListener(new java.awt.event.MouseAdapter() {
                 public void mouseClicked(java.awt.event.MouseEvent evt) {
                     int linha = TabelaMusicasCurtidas.getSelectedRow();
                     String nome = TabelaMusicasCurtidas.getValueAt(linha, 0).toString();
                     String artista = TabelaMusicasCurtidas.getValueAt(linha, 1).toString();

                     DetalheMusicCurtida detalhes = new DetalheMusicCurtida(nome, artista, MusicasCurtidas.this);
                     detalhes.setLocationRelativeTo(null);
                     detalhes.setVisible(true);
                 }
             });

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMusicasCurtidas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BoxNomeMusica_ft = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BoxArtista_ft = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BoxGenero_ft = new javax.swing.JTextField();
        BotaoBuscar_ft_musicasCurtidas = new javax.swing.JButton();
        BotaoVoltar_MusicasCurtidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Musicas curtidas");
        jLabel1.setOpaque(true);

        TabelaMusicasCurtidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome da Musica", "Artista", "Genero", "Tempo de Musica"
            }
        ));
        jScrollPane1.setViewportView(TabelaMusicasCurtidas);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome da Musica");

        BoxNomeMusica_ft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNomeMusica_ftActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Artista");

        BoxArtista_ft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxArtista_ftActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gênero");

        BoxGenero_ft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGenero_ftActionPerformed(evt);
            }
        });

        BotaoBuscar_ft_musicasCurtidas.setBackground(new java.awt.Color(0, 204, 51));
        BotaoBuscar_ft_musicasCurtidas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscar_ft_musicasCurtidas.setText("Buscar");
        BotaoBuscar_ft_musicasCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscar_ft_musicasCurtidasActionPerformed(evt);
            }
        });

        BotaoVoltar_MusicasCurtidas.setBackground(new java.awt.Color(255, 51, 51));
        BotaoVoltar_MusicasCurtidas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVoltar_MusicasCurtidas.setText("Voltar");
        BotaoVoltar_MusicasCurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltar_MusicasCurtidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(BoxNomeMusica_ft, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(BoxArtista_ft, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BoxGenero_ft, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoBuscar_ft_musicasCurtidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoVoltar_MusicasCurtidas)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxNomeMusica_ft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxGenero_ft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoBuscar_ft_musicasCurtidas)
                            .addComponent(BotaoVoltar_MusicasCurtidas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BoxArtista_ft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxNomeMusica_ftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNomeMusica_ftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNomeMusica_ftActionPerformed

    private void BoxArtista_ftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxArtista_ftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxArtista_ftActionPerformed

    private void BoxGenero_ftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGenero_ftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxGenero_ftActionPerformed

    private void BotaoBuscar_ft_musicasCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscar_ft_musicasCurtidasActionPerformed

    }//GEN-LAST:event_BotaoBuscar_ft_musicasCurtidasActionPerformed

    private void BotaoVoltar_MusicasCurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltar_MusicasCurtidasActionPerformed

    }//GEN-LAST:event_BotaoVoltar_MusicasCurtidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicasCurtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicasCurtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicasCurtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicasCurtidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicasCurtidas().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscar_ft_musicasCurtidas;
    private javax.swing.JButton BotaoVoltar_MusicasCurtidas;
    private javax.swing.JTextField BoxArtista_ft;
    private javax.swing.JTextField BoxGenero_ft;
    private javax.swing.JTextField BoxNomeMusica_ft;
    private javax.swing.JTable TabelaMusicasCurtidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
