/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author igorb
 */

import DAO.AddNovMusicPlaylistSelect;
import DAO.ExcluirMusicaPlaylist;
import DAO.ListaMusicasPlaylistSelect;
import DAO.MusicaDao;
import java.awt.event.ActionEvent;
public class TelaColocarMusicaPlaylist extends javax.swing.JFrame {

public TelaColocarMusicaPlaylist(String nomePlaylist) {
    
    initComponents();
    
    

    BoxPlayListSelecionada.setText(nomePlaylist);
    String nomePlayListSelecionada = nomePlaylist;

    ListaMusicasPlaylistSelect lista = new ListaMusicasPlaylistSelect();
    lista.CarregarMusicasPlaylistSelect(TabelaMusicasPlaylist, nomePlayListSelecionada);

    TabelaMusicasBD.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = TabelaMusicasBD.getSelectedRow();
            String nome = TabelaMusicasBD.getValueAt(linha, 1).toString();
            BoxMusicaSelecionada.setText(nome);
        }
    });

    TabelaMusicasPlaylist.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = TabelaMusicasPlaylist.getSelectedRow();
            String nome_musica = TabelaMusicasPlaylist.getValueAt(linha, 0).toString();
            BoxMusicaSelecionada.setText(nome_musica);
        }
    });

    MusicaDao dao = new MusicaDao();
    dao.carregarMusicas(TabelaMusicasBD);
}
public TelaColocarMusicaPlaylist() {
    initComponents();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ListaMusicasSalvas = new javax.swing.JScrollPane();
        TabelaMusicasPlaylist = new javax.swing.JTable();
        ListaMusicasSalvas1 = new javax.swing.JScrollPane();
        TabelaMusicasBD = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BoxMusicaSelecionada = new javax.swing.JTextField();
        BotaoAdicionarMusicaPlaylist = new javax.swing.JButton();
        BotaoCancelAddPll = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BoxPlayListSelecionada = new javax.swing.JTextField();
        BotaoRemoverPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar musicas na playlist selecionada");
        jLabel1.setOpaque(true);

        TabelaMusicasPlaylist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome da Musica"
            }
        ));
        ListaMusicasSalvas.setViewportView(TabelaMusicasPlaylist);

        TabelaMusicasBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome da Musica"
            }
        ));
        ListaMusicasSalvas1.setViewportView(TabelaMusicasBD);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("                                                                        Lista de Musicas");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                                                       Musicas salvas na playlist");
        jLabel3.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Musica selecionada");

        BotaoAdicionarMusicaPlaylist.setBackground(new java.awt.Color(51, 255, 51));
        BotaoAdicionarMusicaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAdicionarMusicaPlaylist.setText("Adicionar");
        BotaoAdicionarMusicaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarMusicaPlaylistActionPerformed(evt);
            }
        });

        BotaoCancelAddPll.setBackground(new java.awt.Color(255, 0, 51));
        BotaoCancelAddPll.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCancelAddPll.setText("Cancelar");
        BotaoCancelAddPll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelAddPllActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Playlist Selecionada:");

        BotaoRemoverPlaylist.setBackground(new java.awt.Color(255, 153, 0));
        BotaoRemoverPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        BotaoRemoverPlaylist.setText("Remover da Playlist");
        BotaoRemoverPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRemoverPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ListaMusicasSalvas1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaMusicasSalvas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(475, 475, 475)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoxPlayListSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BoxMusicaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotaoCancelAddPll)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoRemoverPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAdicionarMusicaPlaylist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BoxPlayListSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoxMusicaSelecionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCancelAddPll)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotaoAdicionarMusicaPlaylist)
                        .addComponent(BotaoRemoverPlaylist)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaMusicasSalvas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ListaMusicasSalvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAdicionarMusicaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarMusicaPlaylistActionPerformed
        // TODO add your handling code here:

        String playlist = BoxPlayListSelecionada.getText();
        String musica = BoxMusicaSelecionada.getText();

 
        AddNovMusicPlaylistSelect dao = new AddNovMusicPlaylistSelect();
        dao.adicionarMusicaNaPlaylist(playlist, musica);

        ListaMusicasPlaylistSelect lista = new ListaMusicasPlaylistSelect();
        lista.CarregarMusicasPlaylistSelect(TabelaMusicasPlaylist, playlist);

    }//GEN-LAST:event_BotaoAdicionarMusicaPlaylistActionPerformed

    private void BotaoRemoverPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoRemoverPlaylistActionPerformed
        // TODO add your handling code here:
        String playlist = BoxPlayListSelecionada.getText();
        String musica = BoxMusicaSelecionada.getText();

        // Remove do banco
        ExcluirMusicaPlaylist dao = new ExcluirMusicaPlaylist();
        dao.ExcluirMscPll(playlist, musica);

        // Atualiza a tabela de músicas da playlist
        ListaMusicasPlaylistSelect lista = new ListaMusicasPlaylistSelect();
        lista.CarregarMusicasPlaylistSelect(TabelaMusicasPlaylist, playlist);

    }//GEN-LAST:event_BotaoRemoverPlaylistActionPerformed

    private void BotaoCancelAddPllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelAddPllActionPerformed
        // TODO add your handling code here:
        TelaPlaylistsGerais telapllg = new TelaPlaylistsGerais();
        telapllg.setLocationRelativeTo(null);
        telapllg.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BotaoCancelAddPllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaColocarMusicaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaColocarMusicaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaColocarMusicaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaColocarMusicaPlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new TelaColocarMusicaPlaylist().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarMusicaPlaylist;
    private javax.swing.JButton BotaoCancelAddPll;
    private javax.swing.JButton BotaoRemoverPlaylist;
    private javax.swing.JTextField BoxMusicaSelecionada;
    private javax.swing.JTextField BoxPlayListSelecionada;
    private javax.swing.JScrollPane ListaMusicasSalvas;
    private javax.swing.JScrollPane ListaMusicasSalvas1;
    private javax.swing.JTable TabelaMusicasBD;
    private javax.swing.JTable TabelaMusicasPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
