/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ListaPlaylist;

/**
 *
 * @author igorb
 */
public class TelaPlaylistsGerais extends javax.swing.JFrame {

    /**
     * Creates new form TelaPlaylistsGerais
     */
    public TelaPlaylistsGerais() {
        initComponents();
        
        ListaPlaylist dao = new ListaPlaylist();
        dao.CarregarListaPlaylists(TabelaListaDePlaylists);
        
        TabelaListaDePlaylists.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int linha = TabelaListaDePlaylists.getSelectedRow();
        if (linha >= 0) {
            String nomePlaylist = TabelaListaDePlaylists.getValueAt(linha, 0).toString();

            TelaColocarMusicaPlaylist tela = new TelaColocarMusicaPlaylist(nomePlaylist);
            tela.setLocationRelativeTo(null);
            tela.setVisible(true);

            dispose(); // Fecha esta tela
        }
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaListaDePlaylists = new javax.swing.JTable();
        BotaoBuscaPlaylist = new javax.swing.JButton();
        BotaoVoltarPlaylist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BoxNomePlaylist = new javax.swing.JTextField();
        BotaoNovaPlaylist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        TabelaListaDePlaylists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome da Playlist"
            }
        ));
        jScrollPane1.setViewportView(TabelaListaDePlaylists);

        BotaoBuscaPlaylist.setBackground(new java.awt.Color(0, 204, 51));
        BotaoBuscaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        BotaoBuscaPlaylist.setText("Buscar");
        BotaoBuscaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoBuscaPlaylistActionPerformed(evt);
            }
        });

        BotaoVoltarPlaylist.setBackground(new java.awt.Color(255, 51, 51));
        BotaoVoltarPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVoltarPlaylist.setText("Voltar");
        BotaoVoltarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarPlaylistActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome da Playlists");

        BoxNomePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNomePlaylistActionPerformed(evt);
            }
        });

        BotaoNovaPlaylist.setBackground(new java.awt.Color(0, 204, 51));
        BotaoNovaPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovaPlaylist.setText("Nova Playlist");
        BotaoNovaPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoNovaPlaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BoxNomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(BotaoBuscaPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoVoltarPlaylist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(BotaoNovaPlaylist)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxNomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoBuscaPlaylist)
                    .addComponent(BotaoVoltarPlaylist)
                    .addComponent(BotaoNovaPlaylist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoBuscaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoBuscaPlaylistActionPerformed
        //Buscar nos filtdos
        
    }//GEN-LAST:event_BotaoBuscaPlaylistActionPerformed

    private void BotaoVoltarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarPlaylistActionPerformed
        // TODO add your handling code here:
        
        TelaInicial telainit = new TelaInicial();
        telainit.setVisible(true);
        telainit.setLocationRelativeTo(null);
        dispose();
   
    }//GEN-LAST:event_BotaoVoltarPlaylistActionPerformed

    private void BoxNomePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNomePlaylistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNomePlaylistActionPerformed

    private void BotaoNovaPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovaPlaylistActionPerformed
        // TODO add your handling code here:
                
        CriarPlaylist criarplls = new CriarPlaylist();
        criarplls.setVisible(true);
        criarplls.setLocationRelativeTo(null);
        dispose();
   
    }//GEN-LAST:event_BotaoNovaPlaylistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPlaylistsGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPlaylistsGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPlaylistsGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPlaylistsGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPlaylistsGerais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoBuscaPlaylist;
    private javax.swing.JButton BotaoNovaPlaylist;
    private javax.swing.JButton BotaoVoltarPlaylist;
    private javax.swing.JTextField BoxNomePlaylist;
    private javax.swing.JTable TabelaListaDePlaylists;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
